require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe MaterialGroupsController do

  # This should return the minimal set of attributes required to create a valid
  # MaterialGroup. As you add validations to MaterialGroup, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "name" => "MyString" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # MaterialGroupsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all material_groups as @material_groups" do
      material_group = MaterialGroup.create! valid_attributes
      get :index, {}, valid_session
      assigns(:material_groups).should eq([material_group])
    end
  end

  describe "GET show" do
    it "assigns the requested material_group as @material_group" do
      material_group = MaterialGroup.create! valid_attributes
      get :show, {:id => material_group.to_param}, valid_session
      assigns(:material_group).should eq(material_group)
    end
  end

  describe "GET new" do
    it "assigns a new material_group as @material_group" do
      get :new, {}, valid_session
      assigns(:material_group).should be_a_new(MaterialGroup)
    end
  end

  describe "GET edit" do
    it "assigns the requested material_group as @material_group" do
      material_group = MaterialGroup.create! valid_attributes
      get :edit, {:id => material_group.to_param}, valid_session
      assigns(:material_group).should eq(material_group)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new MaterialGroup" do
        expect {
          post :create, {:material_group => valid_attributes}, valid_session
        }.to change(MaterialGroup, :count).by(1)
      end

      it "assigns a newly created material_group as @material_group" do
        post :create, {:material_group => valid_attributes}, valid_session
        assigns(:material_group).should be_a(MaterialGroup)
        assigns(:material_group).should be_persisted
      end

      it "redirects to the created material_group" do
        post :create, {:material_group => valid_attributes}, valid_session
        response.should redirect_to(MaterialGroup.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved material_group as @material_group" do
        # Trigger the behavior that occurs when invalid params are submitted
        MaterialGroup.any_instance.stub(:save).and_return(false)
        post :create, {:material_group => { "name" => "invalid value" }}, valid_session
        assigns(:material_group).should be_a_new(MaterialGroup)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        MaterialGroup.any_instance.stub(:save).and_return(false)
        post :create, {:material_group => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested material_group" do
        material_group = MaterialGroup.create! valid_attributes
        # Assuming there are no other material_groups in the database, this
        # specifies that the MaterialGroup created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        MaterialGroup.any_instance.should_receive(:update_attributes).with({ "name" => "MyString" })
        put :update, {:id => material_group.to_param, :material_group => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested material_group as @material_group" do
        material_group = MaterialGroup.create! valid_attributes
        put :update, {:id => material_group.to_param, :material_group => valid_attributes}, valid_session
        assigns(:material_group).should eq(material_group)
      end

      it "redirects to the material_group" do
        material_group = MaterialGroup.create! valid_attributes
        put :update, {:id => material_group.to_param, :material_group => valid_attributes}, valid_session
        response.should redirect_to(material_group)
      end
    end

    describe "with invalid params" do
      it "assigns the material_group as @material_group" do
        material_group = MaterialGroup.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        MaterialGroup.any_instance.stub(:save).and_return(false)
        put :update, {:id => material_group.to_param, :material_group => { "name" => "invalid value" }}, valid_session
        assigns(:material_group).should eq(material_group)
      end

      it "re-renders the 'edit' template" do
        material_group = MaterialGroup.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        MaterialGroup.any_instance.stub(:save).and_return(false)
        put :update, {:id => material_group.to_param, :material_group => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested material_group" do
      material_group = MaterialGroup.create! valid_attributes
      expect {
        delete :destroy, {:id => material_group.to_param}, valid_session
      }.to change(MaterialGroup, :count).by(-1)
    end

    it "redirects to the material_groups list" do
      material_group = MaterialGroup.create! valid_attributes
      delete :destroy, {:id => material_group.to_param}, valid_session
      response.should redirect_to(material_groups_url)
    end
  end

end
